# Numpy arange

In [1]:
import numpy as np

In [2]:
x=np.arange(5)
print(x)

[0 1 2 3 4]


In [3]:
y=np.arange(5,dtype=complex)
print(y)

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [4]:
print(len(x))
print(len(y))

5
5


In [6]:
a=np.arange(5,10,2)
print(a)

[5 7 9]


### linspace

In [12]:
x=np.linspace(10,20,21)
print(x)
y=np.logspace(0,10,num=10,base=2)
print(y)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20. ]
[1.00000000e+00 2.16011948e+00 4.66611616e+00 1.00793684e+01
 2.17726400e+01 4.70315038e+01 1.01593667e+02 2.19454460e+02
 4.74047853e+02 1.02400000e+03]


### Indexing

In [13]:
z=x[5::3]

In [14]:
print(z)
sum=0
for i in range (len(z)):
    sum=sum+z[i]
print("Sum of the items in array z is :",sum)

[12.5 14.  15.5 17.  18.5 20. ]
Sum of the items in array z is : 97.5


In [15]:
b=slice(5,20,3)
print(x[b])

[12.5 14.  15.5 17.  18.5]


In [16]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [23]:
z=a[1:]
print(z)

[[3 4 5]
 [6 7 8]]


In [29]:
w=a[:1]
print(w)

[[1 2 3]]


In [30]:
u=a[:,:-1]
print(u)

[[1 2]
 [3 4]
 [6 7]]


In [31]:
p=a[:-1]
print(p)

[[1 2 3]
 [3 4 5]]
