In [1]:
import numpy as np

a=np.array([1.0,2.2,5.5,123,0.3,0.567,25.532])

print(a)

##round operation
print(np.around(a))
print(np.around(a, decimals=1))
print(a)
print(np.around(a, decimals=-1))

####ceil() and floor() functions
c=np.array([-1.7,1.5,-0.2,0.6,10])

print(c)
print(np.ceil(c))
print(np.floor(c))

z=1.3
b=z+.5
print(b)
print(int(b))
print(int(z+.5))

[  1.      2.2     5.5   123.      0.3     0.567  25.532]
[  1.   2.   6. 123.   0.   1.  26.]
[  1.    2.2   5.5 123.    0.3   0.6  25.5]
[  1.      2.2     5.5   123.      0.3     0.567  25.532]
[  0.   0.  10. 120.   0.   0.  30.]
[-1.7  1.5 -0.2  0.6 10. ]
[-1.  2. -0.  1. 10.]
[-2.  1. -1.  0. 10.]
1.8
1
1
