# Numpy Broadcasting

In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])

In [10]:
c=a*b
print(c)

[ 10  40  90 160 250]


In [11]:
x=np.array([[10,20,30],[40,50,60],[70,80,90]])
y=np.array([[1,2,3]])
print("array x is:\n",x)
print("array y is:\n",y)

array x is:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
array y is:
 [[1 2 3]]


In [12]:
z=x+y

In [13]:
print("Original matrix is\n",x)
print("After performing addition on x\n",z)

Original matrix is
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
After performing addition on x
 [[11 22 33]
 [41 52 63]
 [71 82 93]]


In [15]:
a=np.arange(0,60,5)
a=a.reshape(3,4)

print("First array is:")
print(a)
print("\n")

print("Second array is:")
b=np.array([1,2,3,4],dtype=int)
print(b)
print("\n")

print("Modified array is:")
for x,y in np.nditer([a,b]):
    print("%d:%d" % (x,y))

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4
