# Numpy Datatype

In [2]:
import numpy as np

In [4]:
a=[1,2,3,4,5]
b=np.array(a, dtype=float)
print(a)
print(b)

[1, 2, 3, 4, 5]
[1. 2. 3. 4. 5.]


In [6]:
dt=np.dtype([('age',np.int8)])

In [7]:
x=np.array([(10,),(20,),(30,),(200,)],dtype=dt)

In [8]:
print(x)

[( 10,) ( 20,) ( 30,) (-56,)]


In [9]:
print(x['age'])

[ 10  20  30 -56]


In [ ]:
#### Create structure data named student
##### name = datatype-string -S20
##### age = integer
##### marks = float

# Numpy Attributes

##### .shape = tells about array dimension
##### .reshape = to resize array

In [11]:
import numpy as np

In [12]:
a=np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


In [14]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape)

(3, 3)


In [15]:
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


#### reshape

In [18]:
x=np.array([1,2,3,4,5,6,7,8])
y=x.reshape(4,2)
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
z=y.reshape(2,4)
print(z)

[[1 2 3 4]
 [5 6 7 8]]


### ndim = returns the number of array dimensions

In [20]:
print(z.ndim)

2


In [21]:
print(y.ndim)

2


In [22]:
print(a.ndim)

2


In [27]:
p=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print(p)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [28]:
print(p.ndim)

3


### arange

In [30]:
w=np.arange(24,dtype=float)
print(w)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [31]:
print(w.ndim)

1


In [32]:
v=w.reshape(2,4,3)
print(v)
print(v.ndim)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[12. 13. 14.]
  [15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]]]
3


### itemsize

In [33]:
print(a.itemsize)

4


In [34]:
print(w.itemsize)

8


In [35]:
print(v.itemsize)

8
