# Numpy
## ndarray -> n dimensional array

In [2]:
import numpy as np

In [3]:
# np.array(object,dtype=None,copy=True,order=None(C/F/A),subok=False,ndmin=0)

In [4]:
a=np.array([1,2,3,4,5])

In [7]:
b=np.array([[1,2],[12,13]])

In [10]:
f=np.array([[1,2],[12,13]],dtype=int)
print (f)

[[ 1  2]
 [12 13]]


In [11]:
print(a)

[1 2 3 4 5]


In [12]:
print(b)

[[ 1  2]
 [12 13]]


## Using ndmin

In [13]:
c=np.array([1,2,3,4,5],ndmin=2)

In [14]:
print(c)

[[1 2 3 4 5]]


# Using dtype (datatype of array)

In [15]:
d=np.array([1,2,3,4,5],dtype=complex)

In [16]:
print(d)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


#### Reverse of given array

In [21]:
z=np.array([1,2,3,4,5])[::-1]
print(z)
print(len(z))

[5 4 3 2 1]
5


In [22]:
sum=0
for i in range(len(a)):
    sum+=a[i]
print(sum)

15
